"""phase4 claims and matches

Revision ID: 694b4d0375ad
Revises: 06689f36b9bc
Create Date: 2026-09-20 03:02:03.860527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '694b4d0375ad'
down_revision: Union[str, None] = '06689f36b9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_claims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alobot_payment_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expected_amount_irr', sa.BigInteger(), nullable=False),
    sa.Column('ibsng_username', sa.String(length=64), nullable=False),
    sa.Column('invoice_code', sa.String(length=32), nullable=True),
    sa.Column('target_card_number', sa.String(length=16), nullable=True),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('paid_clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='PENDING', nullable=False),
    sa.Column('alobot_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('alobot_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('continuity', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('suspect_reason', sa.String(length=48), nullable=True),
    sa.Column('candidate_transaction_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('parked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messaged_template', sa.String(length=48), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'AUTO_VERIFIED', 'MANUAL_VERIFIED', 'REJECTED', 'FAKE', 'FULFILLED_UNRECONCILED')", name='payment_claims_status_check'),
    sa.CheckConstraint('expected_amount_irr >= 0', name='payment_claims_amount_check'),
    sa.ForeignKeyConstraint(['target_account_id'], ['financial_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alobot_payment_id')
    )
    op.create_index('ix_payment_claims_status_paid', 'payment_claims', ['status', 'paid_clicked_at'], unique=False)
    op.create_index('ix_payment_claims_telegram', 'payment_claims', ['telegram_id'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('time_delta_seconds', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SUGGESTED', 'AUTO_VERIFIED', 'CONFIRMED', 'REJECTED')", name='reconciliation_matches_status_check'),
    sa.ForeignKeyConstraint(['claim_id'], ['payment_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_matches_claim', 'reconciliation_matches', ['claim_id'], unique=False)
    op.create_index('uq_match_one_settling_per_claim', 'reconciliation_matches', ['claim_id'], unique=True, postgresql_where="status IN ('AUTO_VERIFIED', 'CONFIRMED')")
    op.create_index('uq_match_one_settling_per_transaction', 'reconciliation_matches', ['transaction_id'], unique=True, postgresql_where="status IN ('AUTO_VERIFIED', 'CONFIRMED')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_match_one_settling_per_transaction', table_name='reconciliation_matches', postgresql_where="status IN ('AUTO_VERIFIED', 'CONFIRMED')")
    op.drop_index('uq_match_one_settling_per_claim', table_name='reconciliation_matches', postgresql_where="status IN ('AUTO_VERIFIED', 'CONFIRMED')")
    op.drop_index('ix_reconciliation_matches_claim', table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index('ix_payment_claims_telegram', table_name='payment_claims')
    op.drop_index('ix_payment_claims_status_paid', table_name='payment_claims')
    op.drop_table('payment_claims')
    # ### end Alembic commands ###
