"""phase7 reseller topups

Revision ID: 9562091866c4
Revises: 76d334e0ea8f
Create Date: 2026-09-20 15:17:35.544470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9562091866c4'
down_revision: Union[str, None] = '76d334e0ea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller_topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_irr', sa.BigInteger(), nullable=False),
    sa.Column('balance_before_irr', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_irr', sa.BigInteger(), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_email', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_irr > 0', name='reseller_topups_amount_positive'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reseller_topups_telegram_id'), 'reseller_topups', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reseller_topups_telegram_id'), table_name='reseller_topups')
    op.drop_table('reseller_topups')
    # ### end Alembic commands ###
