"""phase3 sms pipeline tables

Revision ID: 06689f36b9bc
Revises: bb0907a17272
Create Date: 2026-09-20 02:44:59.764278
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '06689f36b9bc'
down_revision: Union[str, None] = 'bb0907a17272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_card_prefixes',
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=254), nullable=True),
    sa.CheckConstraint("prefix ~ '^[0-9]{4,8}$'", name='bank_card_prefixes_prefix_check'),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('bank_sms_patterns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('detect_re', sa.String(length=500), nullable=False),
    sa.Column('amount_re', sa.String(length=500), nullable=False),
    sa.Column('amount_unit', sa.String(length=8), server_default='IRR', nullable=False),
    sa.Column('direction', sa.String(length=8), server_default='CREDIT', nullable=False),
    sa.Column('balance_re', sa.String(length=500), nullable=True),
    sa.Column('account_re', sa.String(length=500), nullable=True),
    sa.Column('reference_re', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=254), nullable=True),
    sa.CheckConstraint("amount_unit IN ('IRR', 'TOMAN')", name='bank_sms_patterns_unit_check'),
    sa.CheckConstraint("direction IN ('CREDIT', 'DEBIT')", name='bank_sms_patterns_direction_check'),
    sa.CheckConstraint("id ~ '^[a-z0-9][a-z0-9_-]{0,63}$'", name='bank_sms_patterns_id_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_auth_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED')", name='device_credentials_status_check'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_device_credentials_prefix', 'device_credentials', ['token_prefix'], unique=False)
    op.create_index('uq_device_credentials_one_active', 'device_credentials', ['device_id'], unique=True, postgresql_where="status = 'ACTIVE'")
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('owner_label', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('inferred_from_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'MUTED', 'DECLINED')", name='financial_accounts_status_check'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('sms_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classification', sa.String(length=24), nullable=False),
    sa.Column('parser_id', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=16), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("classification IN ('BANK_TRANSACTION', 'BALANCE', 'OTP', 'PROMOTIONAL', 'UNKNOWN')", name='sms_events_classification_check'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_sms_events_device_time', 'sms_events', ['device_id', 'sms_timestamp'], unique=False)
    op.create_index('ix_sms_events_received', 'sms_events', ['received_at'], unique=False)
    op.create_table('financial_account_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('CARD', 'CARD_LAST4', 'ACCOUNT', 'ACCOUNT_LAST4', 'IBAN', 'OTHER')", name='financial_account_identifiers_kind_check'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_financial_account_identifiers_kind_value')
    )
    op.create_index(op.f('ix_financial_account_identifiers_account_id'), 'financial_account_identifiers', ['account_id'], unique=False)
    op.create_table('payment_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('holder_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("card_number ~ '^[0-9]{16}$'", name='payment_cards_number_check'),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name='payment_cards_status_check'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_index(op.f('ix_payment_cards_account_id'), 'payment_cards', ['account_id'], unique=False)
    op.create_table('transaction_candidates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sms_event_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('inferred_account_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_irr', sa.BigInteger(), nullable=True),
    sa.Column('balance_irr', sa.BigInteger(), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('account_hint', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('bank_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('parser_id', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=16), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disposition', sa.String(length=16), server_default='ACTIONABLE', nullable=False),
    sa.Column('disposition_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('CREDIT', 'DEBIT', 'UNKNOWN')", name='transaction_candidates_direction_check'),
    sa.CheckConstraint("disposition IN ('ACTIONABLE', 'DECLINED_INCOME', 'IGNORED')", name='transaction_candidates_disposition_check'),
    sa.CheckConstraint('amount_irr IS NULL OR amount_irr >= 0', name='transaction_candidates_amount_check'),
    sa.CheckConstraint('balance_irr IS NULL OR balance_irr >= 0', name='transaction_candidates_balance_check'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='transaction_candidates_confidence_check'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inferred_account_id'], ['financial_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sms_event_id'], ['sms_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sms_event_id')
    )
    op.create_index('ix_transaction_candidates_account_time', 'transaction_candidates', ['account_id', 'bank_timestamp'], unique=False)
    op.create_index('ix_transaction_candidates_amount', 'transaction_candidates', ['amount_irr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_candidates_amount', table_name='transaction_candidates')
    op.drop_index('ix_transaction_candidates_account_time', table_name='transaction_candidates')
    op.drop_table('transaction_candidates')
    op.drop_index(op.f('ix_payment_cards_account_id'), table_name='payment_cards')
    op.drop_table('payment_cards')
    op.drop_index(op.f('ix_financial_account_identifiers_account_id'), table_name='financial_account_identifiers')
    op.drop_table('financial_account_identifiers')
    op.drop_index('ix_sms_events_received', table_name='sms_events')
    op.drop_index('ix_sms_events_device_time', table_name='sms_events')
    op.drop_table('sms_events')
    op.drop_table('financial_accounts')
    op.drop_index('uq_device_credentials_one_active', table_name='device_credentials', postgresql_where="status = 'ACTIVE'")
    op.drop_index('ix_device_credentials_prefix', table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_table('devices')
    op.drop_table('bank_sms_patterns')
    op.drop_table('bank_card_prefixes')
    # ### end Alembic commands ###
