"""phase5 broadcasts

Revision ID: 76d334e0ea8f
Revises: 694b4d0375ad
Create Date: 2026-09-20 12:54:42.378912
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76d334e0ea8f'
down_revision: Union[str, None] = '694b4d0375ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'SENDING', 'DONE')", name='broadcasts_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED')", name='broadcast_recipients_status_check'),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'chat_id', name='uq_broadcast_recipient')
    )
    op.create_index('ix_broadcast_recipients_pending', 'broadcast_recipients', ['broadcast_id'], unique=False, postgresql_where="status = 'PENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_broadcast_recipients_pending', table_name='broadcast_recipients', postgresql_where="status = 'PENDING'")
    op.drop_table('broadcast_recipients')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
